# Generated by Django 2.0.4 on 2018-05-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageScrape',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
