# Generated by Django 2.0.4 on 2018-05-06 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movichome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagescrape',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
