# Generated by Django 2.0.4 on 2018-05-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movichome', '0002_pagescrape_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagescrape',
            name='title',
        ),
    ]
