# Generated by Django 2.0.4 on 2018-05-06 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movichome', '0004_pagescrape_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagescrape',
            name='description_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
